### ISSUE TITLE
Managing resources IRIs with anchors

### ISSUE THREAD

**Issue by luigi-asprino** [dvcama/LodView#22]
Hi,

Actually I do not know if it is a real issue.

Suppose that you want to dereferenciate an IRI like 

http://example.org/data#resource1

According to this [RFC](http://www.ietf.org/rfc/rfc1738.txt) #resource1 is sent to the server after the page has been loaded.
In fact using default configuration when accessing to http://example.org/data#resource1 LodView shows information realated to http://example.org/data because it does not receive #resource1

Is there any way to overcome this issue? 

Thank you 

Luigi

**Comment by dvcama** [comment]
Hi,

so the main problem is that, as far as I know, the fragment after "#" is never sent to the server, so LodView is not able to detect it at all. 
The only thing I can think of is some javascript code that, after detecting the fragment client side, redirects the browser to an encoded version of the url. The problem is that LodView is not just for people, we made it for machines too and this javascript mechanism will never work so I'm not really interested in developing it.
IRIs based on "#" instead of "/" are really uncomfortable to manage and at the end of the day you should avoid them in publications bigger then an ontology... 

... I should implement a different rendering system able to show all resources listed in http://example.org/data and let the browser handle the viewport, I never did that because I'd like to release an ontology viewer instead, sadly I never had time for that!
