### ISSUE TITLE
is sparql and IRI params in query string working?

### ISSUE THREAD

**Issue by ecow** [dvcama/LodView#35]
Hi, lodview.it accepts some extra parameters in the query string of URL (i.e. sparql, IRI, etc.). Is this a feature that works  also in gitub distribution?

**Comment by dvcama** [comment]
no, the feature is not included... do you need it?

**Comment by ecow** [comment]
Yes, I would like to host multi domain lodview  instance (i.e. a mirror of lodview.it)  because happens that  lodview.it server is slow or it is down.

**Comment by dvcama** [comment]
write me on diego@lodview.it so we can talk about it

**Comment by edmondchuc** [comment]
Hi @dvcama, is it possible to self-host LodView with the query string parameter functionality? 

I am asking because there seems to be some issues with the SSL certificate at https://lodview.it/ at the moment (2022-08-19). Essentially, I'm in the same predicament as @ecow and I would like to see if it's possible to set up a mirror of lodview.it.
